cju7f9umg2olj0987fj5y285w.*
cju7f9umg2olj0987fj5y285w.*
cju5von04litr08718j8po40a.*
cju5von04litr08718j8po40a.*
102.*
102.*
8.*
8.*
102  ----load----
cju5von04litr08718j8po40a  ----load----
8  ----load----
img: (384, 288)
img: (622, 530)
img: (384, 288)
mask: (384, 288)
mask: (622, 530)
mask: (384, 288)
cju7f9umg2olj0987fj5y285w  ----load----
img: (622, 529)
mask: (622, 529)
cju2pjb9v0ywn0878j5g5n69j.*
cju2pjb9v0ywn0878j5g5n69j.*
cju2pjb9v0ywn0878j5g5n69j  ----load----
img: (622, 529)
mask: (622, 529)
cju84aoa3ktwn0755pfl4gfwd.*
cju84aoa3ktwn0755pfl4gfwd.*
cju84aoa3ktwn0755pfl4gfwd  ----load----
img: (626, 547)
mask: (626, 547)
202.*
202.*
cju85je7vlht70817c9jcjwi4.*
cju85je7vlht70817c9jcjwi4.*
202  ----load----
img: (384, 288)
mask: (384, 288)
cju85je7vlht70817c9jcjwi4  ----load----
img: (1220, 1011)
mask: (1220, 1011)
cju6xmqd9w0250817l5kxfnsk.*
cju6xmqd9w0250817l5kxfnsk.*
cju6xmqd9w0250817l5kxfnsk  ----load----
img: (494, 530)
mask: (494, 530)
INFO: Starting training:
        Epochs:          5
        Batch size:      5
        Learning rate:   1e-05
        Training size:   1305
        Validation size: 145
        Checkpoints:     True
        Device:          cuda
        Images size:     None
        Mixed Precision: True
Epoch 1/5:   0%|                                                                     | 0/1305 [00:00<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 188, in <module>
    amp=args.amp)
  File "train.py", line 76, in train_net
    for batch in train_loader:
  File "/home/nicolas/anaconda3/envs/josue_torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/nicolas/anaconda3/envs/josue_torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/nicolas/anaconda3/envs/josue_torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/nicolas/anaconda3/envs/josue_torch/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/nicolas/anaconda3/envs/josue_torch/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/nicolas/anaconda3/envs/josue_torch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nicolas/anaconda3/envs/josue_torch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nicolas/anaconda3/envs/josue_torch/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 363, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/nicolas/workspace_josue/Pytorch-UNet/utils/data_loading.py", line 77, in __getitem__
    img = self.preprocess(img, self.img_size, is_mask=False)
  File "/home/nicolas/workspace_josue/Pytorch-UNet/utils/data_loading.py", line 30, in preprocess
    print(int(img_size[0]), int(img_size[1]))
TypeError: 'NoneType' object is not subscriptable